### ISSUE TITLE
Cannot install augeas shift lense on fresh install

### ISSUE THREAD

**Issue by kreczko** [cern-it-sdc-id/puppet-lcgdm#9]
On a fresh install (SL 7.2, gateway), the puppet manifest fails on line
https://github.com/cern-it-sdc-id/puppet-lcgdm/blob/master/manifests/base/config.pp#L67
because the `/usr/share/augeas/lenses/dist` does not exist.

**Comment by andrea-manzi** [comment]
i merged the PR which fixes the issues
https://github.com/cern-it-sdc-id/puppet-lcgdm/pull/5
